#!/bin/bash
# ---------------------------------------------------------------------------
# new_script - Bash shell script template generator
#
# Usage: new_script [-h|--help] [-q|--quiet] [-s|--root] [script]
#
# Revision history:
# 2012-05-14    Created
# ---------------------------------------------------------------------------
#defaults
#ARGS=$(getopt -n "$0"  -o hvfon: --long "help,version,force,out,name:"  -- "$@")


PROGNAME=${0##*/}
VERSION="0.1"
SCRIPT_SHELL=${SHELL}
DEFAULT_RELEASE_PATH="./releases/$VERSION/"
DEFAULT_NAME="Onkyo Remote"
#vars for parsing
force=0
version="$VERSION"
out="$DEFAULT_RELEASE_PATH"
name="$DEFAULT_NAME"


# helper methods
usage() {
	echo "Usage: ${PROGNAME} [-h|--help] [-f|--force] [-v|--version] arg [-o|--output] arg [-n|--name] arg"
}

help_message() {
	cat <<- -EOF-
	${PROGNAME} ${VERSION}

	$(usage)

	Options:

	-h, --help      Display this help message and exit.
	-f, --force     Force overwrite of existing widgets, defaults to false.
	-v, --version   Specify version, defaults to "$VERSION", affects release folder.
	-o, --output    Change Output-Folder (defaults to $DEFAULT_RELEASE_PATH).
	-n, --name      Change Widget-Name (defaults to $DEFAULT_NAME).

	-EOF-
}

# parse options
while getopts "hv:fo:n:" options; do
	case $options in
		h)   help_message; exit 0;;
		v)   version=$OPTARG; out="./releases/$version";;
		f)	 force=1;;
		o)	 out=$OPTARG;;
		n)	 name=$OPTARG;;
        \?)  help_message; exit 0;;
	esac
done


main() {
	copy_files
}
copy_files() {
	if [ ! -d "$out" ]; then
		mkdir -p "$out"
	fi
	if [ $force == 0 ] && [ -d "$out/$name.wdgt" ]; then
		name=$name$RANDOM
	fi
	cp -R "./Onyko Remote.wdgt/" "$out/$name.wdgt"
	cp -R "./js" "$out/$name.wdgt"
	cp -R "./img" "$out/$name.wdgt"
	cp -R "./css" "$out/$name.wdgt"
	cp "./index.html" "$out/$name.wdgt"
	cd $out; open .
}
main


